name: Test Python Files
defaults:
  run:
    working-directory: python

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only testing
      - run: poetry run ward test -p tests
