name: Test Python Files

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only dev
      - run: poetry run ward test -p tests
